Repository untilhamza/Booking-Web-App, pull requests merged in 2023-03, with the labels that each got.

#27 Dev/add booking info notification
  public/assets/images/whatsapp/WhatsAppButtonGreenLarge.eps
  public/assets/images/whatsapp/WhatsAppButtonGreenLarge.png
  public/assets/images/whatsapp/WhatsAppButtonGreenLarge.svg
  public/assets/images/whatsapp/WhatsAppButtonGreenMedium.eps
  public/assets/images/whatsapp/WhatsAppButtonGreenMedium.png
  public/assets/images/whatsapp/WhatsAppButtonGreenMedium.svg
  public/assets/images/whatsapp/WhatsAppButtonGreenSmall.eps
  public/assets/images/whatsapp/WhatsAppButtonGreenSmall.png
  public/assets/images/whatsapp/WhatsAppButtonGreenSmall.svg
  src/App.css
  src/components/BookingMenu/BookingMenu.js
  src/components/TrackingCode.js
  src/pages/CheckAppointment.js
  src/pages/Customer.js
  src/pages/NewBooking.js
Labels: enhancement

#29 Release/v1.3.3
  public/assets/images/whatsapp/WhatsAppButtonGreenLarge.eps
  public/assets/images/whatsapp/WhatsAppButtonGreenLarge.png
  public/assets/images/whatsapp/WhatsAppButtonGreenLarge.svg
  public/assets/images/whatsapp/WhatsAppButtonGreenMedium.eps
  public/assets/images/whatsapp/WhatsAppButtonGreenMedium.png
  public/assets/images/whatsapp/WhatsAppButtonGreenMedium.svg
  public/assets/images/whatsapp/WhatsAppButtonGreenSmall.eps
  public/assets/images/whatsapp/WhatsAppButtonGreenSmall.png
  public/assets/images/whatsapp/WhatsAppButtonGreenSmall.svg
  src/App.css
  src/components/BookingMenu/BookingMenu.js
  src/components/TrackingCode.js
  src/pages/CheckAppointment.js
  src/pages/Customer.js
  src/pages/NewBooking.js
  src/version.json
Labels: enhancement

#32 Release/v1.4.0
  src/components/BookingMenu/BookingMenu.js
  src/pages/NewBooking.js
  version.json
Labels: bug

#47 Dev/remove email from booking form
  src/components/BookingForm/BookingForm.js
  src/components/CheckingForm/CheckingForm.js
Labels: enhancement

#48 Release/v1.8.0
  src/components/BookingForm/BookingForm.js
  src/components/CheckingForm/CheckingForm.js
  src/env.json
  version.json
Labels: enhancement

#50 Release/v1.9.0
  .gitignore
  src/components/Booking/Booking.js
  src/components/NavBar/Navbar.js
  src/components/SideBar/SideBar.js
  src/version.json
  version.json
Labels: enhancement

#56 Release/v1.11.0
  package.json
  src/App.js
  src/components/BookingForm/BookingForm.js
  src/components/NavBar/Navbar.js
  src/components/SideBar/SideBar.js
  src/env.json
  src/pages/NewBooking.js
  src/store/auth-context.js
  src/version.json
  yarn.lock
Labels: enhancement

#58 Release/v1.12.0
  src/components/Appointment/Appointment.js
  src/components/Booking/Booking.js
  src/components/BookingForm/BookingForm.js
  src/components/Settings/GeneralSettings.js
  src/components/SideBar/SideBar.js
  src/components/TimeSelector/TimeSelector.js
  src/http/serverInterface.ts
  src/pages/Admin.js
  src/pages/CheckAppointment.js
  src/pages/GeneralSettingsPage.js
  src/pages/NewBooking.js
  src/pages/SlotSettingsPage.js
  src/pages/ViewAppointment.js
  src/store/auth-context.js
  src/utils/data.js
  src/utils/helpers.js
  src/version.json
Labels: enhancement, new feature

#65 Dev/add map directions
  package.json
  public/index.html
  src/App.css
  src/components/BookingMenu/BookingMenu.js
  src/components/MapDirections/MapDirections.tsx
  src/env.json
  src/version.json
  yarn.lock
Labels: new feature
